"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env=environ.Env()
env.read_env(str(BASE_DIR / ".env"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1khiwt$8j23w#a2$hdt82kyjj#-x1#*kgsg97gtf(*&tfhfch+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'home',
    'rest_framework_simplejwt',
    'drf_yasg',
]

SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        }
    }
}

REST_FRAMEWORK = {
 
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
    BASE_DIR / 'covers',
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'





JAZZMIN_SETTINGS = {

    # ==================================================
    # SITE BRANDING
    # ==================================================
    "site_title": "Library Admin",
    "site_header": "Library  System",
    "site_brand": "Library system",


    "welcome_sign": "Library Management System",
    "copyright": "Library Management System",

    # ==================================================
    # SEARCH CONFIGURATION
    # ==================================================
    "search_model": [
        "auth.User",
        "books.Book",
        "books.Author",
        "books.Member",
        "books.Loan",
    ],

    # ==================================================
    # TOP MENU
    # ==================================================
    "topmenu_links": [
        {"name": "Home", "url": "admin:index"},

        {"app": "books"},

        {"model": "auth.User"},

        {"name": "Swagger API", "url": "/swagger/", "new_window": True},
    ],

    # ==================================================
    # SIDEBAR CONFIGURATION
    # ==================================================
    "show_sidebar": True,
    "navigation_expanded": True,

    "order_with_respect_to": [
        "auth",
        "books",
        "books.author",
        "books.book",
        "books.member",
        "books.loan",
    ],

    "hide_apps": [],
    "hide_models": [],

    # ==================================================
    # CUSTOM LINKS (LIBRARY FEATURES)
    # ==================================================
    "custom_links": {
        "books": [
            {
                "name": "Loan Records",
                "url": "admin:books_loan_changelist",
                "icon": "fas fa-hand-holding",
            },
            {
                "name": "Overdue Books",
                "url": "admin:books_loan_changelist",
                "icon": "fas fa-exclamation-circle",
            },
        ]
    },

    # ==================================================
    # ICONS (CLEAN PROFESSIONAL SET)
    # ==================================================
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",

        "books.book": "fas fa-book",
        "books.author": "fas fa-pen",
        "books.member": "fas fa-id-card",
        "books.loan": "fas fa-exchange-alt",
    },

    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-circle",

    # ==================================================
    # UI BEHAVIOR
    # ==================================================
    "related_modal_active": True,
    "language_chooser": False,
    "show_ui_builder": False,

    # ==================================================
    # FORM LAYOUT
    # ==================================================
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
    },
}

SIMPLE_JWT = {
    
    # Access token expires after 5 minutes
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=25),

    # Refresh token expires after 7 days
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),

    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
}

EMAIL_BACKEND ="django.core.mail.backends.smtp.EmailBackend"

EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = env("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")